server:
  port: 8086
  servlet:
    context-path: /imager

spring:
  application:
    name: imager

app:
  s3:
    endpoint: https://-------
    region: us-east-1
    bucket: ------
    accessKey: ------
    secretKey: ------
    pathStyleAccess: true # важно для MinIO
    # Дополнительно: ограничение размера картинок (байты)
    maxSize: 10485760     # 10 MiB по умолчанию
